### ISSUE TITLE
on iPhone X the keyboard will not hide on NativeKeyboard.hideMessenger

### ISSUE THREAD

**Issue by 99electronic** [EddyVerbruggen/cordova-plugin-native-keyboard#97] opened 2018-12-31 22:40 UTC
I noticed that on iPhone X the keyboard does go away but the textinput stays on the bottom of the page. It does not work when I click on it (nothing happens) and there is no way for me to use this plugin since I'm unablw to remove it on another pages. It just stays there. When I open it again , the kayboard appears and I can click on it and use it, but on NativeKeyboard.hideMessenger the keyboard moves away, I go to another page and the textinput is still there.
![img_7712](https://user-images.githubusercontent.com/13053034/50568661-2064bc80-0d23-11e9-935d-e11eca3d797d.jpg)

**Comment by jayordway** [comment] 2019-02-19 08:29
I am seeing this issue as well.

**Comment by smxdevst** [comment] 2019-02-26 23:48
Same here

**Comment by dansiemens** [comment] 2019-03-01 21:48
Same here. Please resolve

**Comment by smxdevst** [comment] 2019-03-01 21:55
This issue were posted on 31 Dec 2018. Still no response from @EddyVerbruggen. 

@EddyVerbruggen if you are charging us a license fee please be polite to react quick enough. Otherwise please provide us a source code so we can maintain it ourselves. We can't be stuck for 2 weeks not able to release application into live because you not taking any actions. Waiting for reply

**Comment by EddyVerbruggen** [comment] 2019-03-01 22:50
@smxdevst I’d be happy to give you access to the source if you’re serious. 

Btw, it’s not meant to be a support license with a service level agreement implying I have to respond within x days. It’s meant to pay for a piece of work done (like a product), and that’s why there’s a demo mode. That being said, I’d love to help out, but my time is extremely limited.

**Comment by smxdevst** [comment] 2019-03-01 23:12
If its not a support license then why code is hidden on a first place. Keep it open source.

Please provide me a source code. Thank you for quick response

**Comment by EddyVerbruggen** [comment] 2019-03-02 09:05
That doesn’t make sense to me. If it’s freely available, how would I make any money off it?

**Comment by jayordway** [comment] 2019-03-02 09:41
Isn't it just the JS file that is uglified/minified? I have concluded that this bug was due to the last PR, specifically for the iOS scroll fix...some new observers were added around the keyboard. I am not sure if the observers should be removed at certain points or if it is a miscalculation of the sizing under certain conditions. The native code is "free" though, right? It could be fixed with another PR...

**Comment by EddyVerbruggen** [comment] 2019-03-02 10:10
What would really help if someone could share a project that reproduces this issue. A simple cloneable repo with instructions goes a long way towards solving the issue.

**Comment by smxdevst** [comment] 2019-03-02 17:11
@EddyVerbruggen If you making money off it please spare some time to fix urgent issues like this. Don't make us lose money. People using your code in production and basically everyone stuck after IOS12.

Here is sample code where you can reproduce it (https://github.com/trane294/nativekeyboard-fix-ios12). 

1) Run with IOS12 on iPhone X simulator. Click Command + K to toggle keyboard
2) Go to Page 1
3) Go back
4) Click searchbar and you would see that messenger bar will appear even I called `hideMessenger` when leaving Page 1

**Comment by intro1987** [comment] 2019-03-03 06:12
I have the same issue.

**Comment by EddyVerbruggen** [comment] 2019-03-03 12:21
@intro1987 The only way a complex issue like this can be solved is by at least demonstrating the actual bug in a project. Thanks to the app @smxdevst shared I may be able to tackle this.

**Comment by EddyVerbruggen** [comment] 2019-03-03 13:47
Give 2.0.1 a shot.

**Closed by EddyVerbruggen** 2019-03-03 13:47 UTC
Labels: bug, iOS

**Comment by chrisfrancis27** [comment] 2019-03-06 15:35
Hey @EddyVerbruggen, cheers for looking into this. I've just discovered the same issue on my app, have updated to 2.0.1 but the issue still remains.

Dismissing the messenger with `NativeKeyboard.hideMessenger()` hides the keyboard successfully but the messenger input box remains partly visible behind the bottom edge. Do you think this could be related to the iPhone X `safe-area-inset-bottom`? I've had to tweak a bunch of CSS to make sure my webview content doesn't go behind the "notch", and the size of the bottom safe area looks suspiciously similar to where the messenger box is... Just a thought!

**Comment by chrisfrancis27** [comment] 2019-03-06 16:02
Also worth noting, the bug only appears on my actual device, simulator seems fine 😑

**Comment by EddyVerbruggen** [comment] 2019-03-06 16:02
@chrisfrancis27 Have you completely removed the platforms/ios folder after upgrading the plugin? If so, and the issue persists, please share a repo.

**Comment by ableabhijeet** [comment] 2019-04-17 04:03
@EddyVerbruggen Any update on this please? We are facing same issue with version 2.0.0.

**Comment by EddyVerbruggen** [comment] 2019-04-17 17:40
@ableabhijeet and 2.0.1?
