### ISSUE TITLE
Not working with WKWebView 

### ISSUE THREAD

**Issue by alantorrisi** [EddyVerbruggen/cordova-plugin-native-keyboard#38] opened 2017-04-19 09:01 UTC
Hi!
The plugin causes the webview crash when any other plugin is used.
Wrote email, tried to call. 
Any advise on where to look to fix this?

**Comment by EddyVerbruggen** [comment] 2017-04-19 13:48
Dupe of #36, please take a look at that issue and try the steps I took. Or provide me with a repo I can clone to reproduce the issue.

**Closed by EddyVerbruggen** 2017-04-19 13:48 UTC
